### ISSUE TITLE
configure imap port and separate email and password

### ISSUE THREAD

**Issue by elbarros** [Rikstone/email_base_checker#1]
an interesting feature and set a wait time between one email and another
every 30 emails wait a while until trying again
set a fixed imap server to hotmail.com (imap-mail.outlook.com)
create a log file with last tested email
user without @ domain.com

**Comment by Rikstone** [comment]
Hi. Some questions:
1.What is the pause for? The algorithm is quite slow already. Afraid of the ban?
2.Okey, i will try add function auto-detect real imap-server or just add file with custom user's redirect
3.Is this your personal request? I see no reason to do this for everyone. But if i will free on my work, i can to do git-branch only for you.
